apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nfs-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config: |-
    exports:
{{- range .Values.nfsExports }}
      - path: {{ .path }}
        squash: {{ .squash }}
{{- end }}
